name: Deploy to GitHub Pages

on:
  push:
    branches:
      - websites

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 检出代码
    - name: Checkout code
      uses: actions/checkout@v3
      with: 
        repository: ${{ github.repository }}
        ref: "websites"
        token: ${{ secrets.GITHUB_TOKEN }}
        
    # 设置 GitHub Pages 的发布路径
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .
