name: Deploy HTML files to GitHub Pages

on:
  push:
    branches:
      - websites

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: websites

      # 部署到GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./websites
          destination_dir: .
          keep_files: false
          force_orphan: true